<input type="button" id = "ask-question-button" class = "action primary tocart" value = "Ask a question" />


<div id="popup-modal">
    <h1> Hi I'm here.... </h1>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup modal title',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
			 $('#ask-question-button').on('click',function(){ 
				$('#popup-modal').modal('openModal'); 
			 });
            
        }
    );
</script>